// src/app/components/card/card.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-card',
  templateUrl: 'card.component.html',
  styleUrls: ['card.component.css'],
})
export class Card {
  @Input()
  Icon: string = '/assets/playground_assets/group%201643.svg'
  @Input()
  Title: string = 'High-impact business services'
  @Input()
  Description: string =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
  constructor() {}
}

<div class="card-card card">
  <div class="card-header">
    <img alt="image" [attr.src]="Icon" class="card-icon" />
    <h3 class="card-heading">{{ Title }}</h3>
  </div>
  <p class="card-text">{{ Description }}</p>
</div>

// components/card.vue
<template>
  <div class="card-card card">
    <div class="card-header">
      <img alt="image" :src="Icon" class="card-icon" />
      <h3 class="card-heading">{{ Title }}</h3>
    </div>
    <p class="card-text">{{ Description }}</p>
  </div>
</template>

<script>
export default {
  name: 'Card',
  props: {
    Icon: {
      type: String,
      default: '/playground_assets/group%201643.svg',
    },
    Title: {
      type: String,
      default: 'High-impact business services',
    },
    Description: {
      type: String,
      default:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
  },
}
</script>

<style scoped>
.card-card {
  position: relative;
}
.card-header {
  gap: var(--dl-space-space-oneandhalfunits);
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.card-icon {
  height: 50px;
  object-fit: cover;
}
.card-heading {
  color: rgb(18, 40, 33);
  font-size: 24px;
  max-width: 600px;
  font-style: normal;
  font-weight: 500;
}
.card-text {
  color: rgb(18, 40, 33);
  max-width: 600px;
  font-family: Lato;
  line-height: 24px;
}
</style>
